/* Copyright Mentor Graphics Corporation 2003

    All Rights Reserved.

 THIS WORK CONTAINS TRADE SECRET
 AND PROPRIETARY INFORMATION WHICH IS THE
 PROPERTY OF MENTOR GRAPHICS
 CORPORATION OR ITS LICENSORS AND IS
 SUBJECT TO LICENSE TERMS. 
*/
//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by CLIENT.RC
//
#define IDR_MAINFRAME					128
#define IDM_ABOUTBOX					0x0010
#define IDD_ABOUTBOX					100
#define IDP_OLE_INIT_FAILED				100
#define IDS_ABOUTBOX					101
#define IDD_CLIENT_DIALOG				102
#define IDC_BTN_CONNECT                 1000
#define IDC_BTN_DISCONNECT              1001
#define IDC_TXT_STATUS                  1002
#define IDC_EDT_APPNAME                 1003
#define IDC_BTN_APPNAME                 1004
#define IDC_BTN_REFRESH                 1004
#define IDC_EDT_DOCNAME                 1005

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1005
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
